<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\UserModel;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run()
    {
        $users = [];

        // 4 Admin users
        $users[] = [
            'nama' => 'Budi Santoso',
            'username' => 'admin1',
            'password' => Hash::make('admin123'),
            'email' => 'budi.santoso@polinema.ac.id',
            'level_id' => 1,
            'profile_photo' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ];
        $users[] = [
            'nama' => 'Siti Aminah',
            'username' => 'admin2',
            'password' => Hash::make('admin123'),
            'email' => 'siti.aminah@polinema.ac.id',
            'level_id' => 1,
            'profile_photo' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ];
        $users[] = [
            'nama' => 'Agus Wijaya',
            'username' => 'admin3',
            'password' => Hash::make('admin123'),
            'email' => 'agus.wijaya@polinema.ac.id',
            'level_id' => 1,
            'profile_photo' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ];
        $users[] = [
            'nama' => 'Rina Susanti',
            'username' => 'admin4',
            'password' => Hash::make('admin123'),
            'email' => 'rina.susanti@polinema.ac.id',
            'level_id' => 1,
            'profile_photo' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ];

        // 100 Mahasiswa users
        $mahasiswa = [
            ['nama' => 'Ahmad Fauzi', 'username' => 'ahmadfauzi1', 'email' => 'ahmad.fauzi1@polinema.ac.id'],
            ['nama' => 'Dewi Lestari', 'username' => 'dewilelstari1', 'email' => 'dewi.lestari1@polinema.ac.id'],
            ['nama' => 'Rizki Pratama', 'username' => 'rizkipratama1', 'email' => 'rizki.pratama1@polinema.ac.id'],
            ['nama' => 'Fitri Rahayu', 'username' => 'fitrirahayu1', 'email' => 'fitri.rahayu1@polinema.ac.id'],
            ['nama' => 'Eko Nugroho', 'username' => 'ekonugroho1', 'email' => 'eko.nugroho1@polinema.ac.id'],
            ['nama' => 'Sari Wulandari', 'username' => 'sariwulandari1', 'email' => 'sari.wulandari1@polinema.ac.id'],
            ['nama' => 'Hendra Kurniawan', 'username' => 'hendrakurniawan1', 'email' => 'hendra.kurniawan1@polinema.ac.id'],
            ['nama' => 'Lina Marlina', 'username' => 'linamarlina1', 'email' => 'lina.marlina1@polinema.ac.id'],
            ['nama' => 'Dedi Setiawan', 'username' => 'dedisetiawan1', 'email' => 'dedi.setiawan1@polinema.ac.id'],
            ['nama' => 'Nia Kurniasih', 'username' => 'niakurniasih1', 'email' => 'nia.kurniasih1@polinema.ac.id'],
            ['nama' => 'Arif Hidayat', 'username' => 'arifhidayat1', 'email' => 'arif.hidayat1@polinema.ac.id'],
            ['nama' => 'Maya Sari', 'username' => 'mayasari1', 'email' => 'maya.sari1@polinema.ac.id'],
            ['nama' => 'Bayu Pratama', 'username' => 'bayupratama1', 'email' => 'bayu.pratama1@polinema.ac.id'],
            ['nama' => 'Rita Permata', 'username' => 'ritapermata1', 'email' => 'rita.permata1@polinema.ac.id'],
            ['nama' => 'Fajar Maulana', 'username' => 'fajarmaulana1', 'email' => 'fajar.maulana1@polinema.ac.id'],
            ['nama' => 'Tina Anggraini', 'username' => 'tinaanggraini1', 'email' => 'tina.anggraini1@polinema.ac.id'],
            ['nama' => 'Yudi Hartono', 'username' => 'yudihartono1', 'email' => 'yudi.hartono1@polinema.ac.id'],
            ['nama' => 'Sinta Dewi', 'username' => 'sintadewi1', 'email' => 'sinta.dewi1@polinema.ac.id'],
            ['nama' => 'Rudi Santoso', 'username' => 'rudisantoso1', 'email' => 'rudi.santoso1@polinema.ac.id'],
            ['nama' => 'Lia Amalia', 'username' => 'liaamalia1', 'email' => 'lia.amalia1@polinema.ac.id'],
            ['nama' => 'Bima Saputra', 'username' => 'bimasaputra1', 'email' => 'bima.saputra1@polinema.ac.id'],
            ['nama' => 'Rina Puspita', 'username' => 'rinapuspita1', 'email' => 'rina.puspita1@polinema.ac.id'],
            ['nama' => 'Adi Nugroho', 'username' => 'adinugroho1', 'email' => 'adi.nugroho1@polinema.ac.id'],
            ['nama' => 'Eka Sari', 'username' => 'ekasari1', 'email' => 'eka.sari1@polinema.ac.id'],
            ['nama' => 'Hasan Basri', 'username' => 'hasanbasri1', 'email' => 'hasan.basri1@polinema.ac.id'],
            ['nama' => 'Lita Dewi', 'username' => 'litadewi1', 'email' => 'lita.dewi1@polinema.ac.id'],
            ['nama' => 'Dwi Santoso', 'username' => 'dwisantoso1', 'email' => 'dwi.santoso1@polinema.ac.id'],
            ['nama' => 'Mira Andini', 'username' => 'miraandini1', 'email' => 'mira.andini1@polinema.ac.id'],
            ['nama' => 'Agung Pratama', 'username' => 'agungpratama1', 'email' => 'agung.pratama1@polinema.ac.id'],
            ['nama' => 'Nia Kurnia', 'username' => 'niakurnia1', 'email' => 'nia.kurnia1@polinema.ac.id'],
            ['nama' => 'Feri Irawan', 'username' => 'feriirawan1', 'email' => 'feri.irawan1@polinema.ac.id'],
            ['nama' => 'Ayu Safitri', 'username' => 'ayusafitri1', 'email' => 'ayu.safitri1@polinema.ac.id'],
            ['nama' => 'Tono Wijaya', 'username' => 'tonowijaya1', 'email' => 'tono.wijaya1@polinema.ac.id'],
            ['nama' => 'Mila Sari', 'username' => 'milasari1', 'email' => 'mila.sari1@polinema.ac.id'],
            ['nama' => 'Rudi Hermawan', 'username' => 'rudihermawan1', 'email' => 'rudi.hermawan1@polinema.ac.id'],
            ['nama' => 'Siti Fatimah', 'username' => 'sitifatimah1', 'email' => 'siti.fatimah1@polinema.ac.id'],
            ['nama' => 'Eko Susilo', 'username' => 'ekosusilo1', 'email' => 'eko.susilo1@polinema.ac.id'],
            ['nama' => 'Ayu Lestari', 'username' => 'ayulestari1', 'email' => 'ayu.lestari1@polinema.ac.id'],
            ['nama' => 'Bima Sakti', 'username' => 'bimasakti1', 'email' => 'bima.sakti1@polinema.ac.id'],
            ['nama' => 'Rina Kurniawati', 'username' => 'rinakurniawati1', 'email' => 'rina.kurniawati1@polinema.ac.id'],
            ['nama' => 'Hadi Santoso', 'username' => 'hadisantoso1', 'email' => 'hadi.santoso1@polinema.ac.id'],
            ['nama' => 'Lina Septiani', 'username' => 'linaseptiani1', 'email' => 'lina.septiani1@polinema.ac.id'],
            ['nama' => 'Andi Prasetyo', 'username' => 'andiprasetyo1', 'email' => 'andi.prasetyo1@polinema.ac.id'],
            ['nama' => 'Sari Indah', 'username' => 'sariindah1', 'email' => 'sari.indah1@polinema.ac.id'],
            ['nama' => 'Budi Hartono', 'username' => 'budihartono1', 'email' => 'budi.hartono1@polinema.ac.id'],
            ['nama' => 'Rina Wulandari', 'username' => 'rinawulandari1', 'email' => 'rina.wulandari1@polinema.ac.id'],
            ['nama' => 'Dedi Kurniawan', 'username' => 'dedikurniawan1', 'email' => 'dedi.kurniawan1@polinema.ac.id'],
            ['nama' => 'Lia Safitri', 'username' => 'liasafitri1', 'email' => 'lia.safitri1@polinema.ac.id'],
            ['nama' => 'Hendra Setiawan', 'username' => 'hendrasetiawan1', 'email' => 'hendra.setiawan1@polinema.ac.id'],
            ['nama' => 'Tina Marlina', 'username' => 'tinamarlina1', 'email' => 'tina.marlina1@polinema.ac.id'],
            ['nama' => 'Fajar Nugroho', 'username' => 'fajarnugroho1', 'email' => 'fajar.nugroho1@polinema.ac.id'],
            ['nama' => 'Mira Puspita', 'username' => 'mirapuspita1', 'email' => 'mira.puspita1@polinema.ac.id'],
            ['nama' => 'Rudi Pratama', 'username' => 'rudipratama1', 'email' => 'rudi.pratama1@polinema.ac.id'],
            ['nama' => 'Siti Rahayu', 'username' => 'sitirahayu1', 'email' => 'siti.rahayu1@polinema.ac.id'],
            ['nama' => 'Eko Wahyudi', 'username' => 'ekowahyudi1', 'email' => 'eko.wahyudi1@polinema.ac.id'],
            ['nama' => 'Ayu Permata', 'username' => 'ayupermata1', 'email' => 'ayu.permata1@polinema.ac.id'],
            ['nama' => 'Bima Nugroho', 'username' => 'bimanugroho1', 'email' => 'bima.nugroho1@polinema.ac.id'],
            ['nama' => 'Rina Anggraini', 'username' => 'rinaanggraini1', 'email' => 'rina.anggraini1@polinema.ac.id'],
            ['nama' => 'Hadi Kurniawan', 'username' => 'hadikurniawan1', 'email' => 'hadi.kurniawan1@polinema.ac.id'],
            ['nama' => 'Lina Wulandari', 'username' => 'linawulandari1', 'email' => 'lina.wulandari1@polinema.ac.id'],
            ['nama' => 'Ahmad Zaki', 'username' => 'ahmadzaki1', 'email' => 'ahmad.zaki1@polinema.ac.id'],
            ['nama' => 'Dewi Safitri', 'username' => 'dewifitri1', 'email' => 'dewi.safitri1@polinema.ac.id'],
            ['nama' => 'Rizki Maulana', 'username' => 'rizkimaulana1', 'email' => 'rizki.maulana1@polinema.ac.id'],
            ['nama' => 'Fitri Anggraini', 'username' => 'fitrianggraini1', 'email' => 'fitri.anggraini1@polinema.ac.id'],
            ['nama' => 'Eko Pratama', 'username' => 'ekopratama1', 'email' => 'eko.pratama1@polinema.ac.id'],
            ['nama' => 'Sari Kurnia', 'username' => 'sarikurnia1', 'email' => 'sari.kurnia1@polinema.ac.id'],
            ['nama' => 'Hendra Wijaya', 'username' => 'hendrawijaya1', 'email' => 'hendra.wijaya1@polinema.ac.id'],
            ['nama' => 'Lina Puspita', 'username' => 'linapuspita1', 'email' => 'lina.puspita1@polinema.ac.id'],
            ['nama' => 'Dedi Nugroho', 'username' => 'dedinugroho1', 'email' => 'dedi.nugroho1@polinema.ac.id'],
            ['nama' => 'Nia Safitri', 'username' => 'niasafitri1', 'email' => 'nia.safitri1@polinema.ac.id'],
            ['nama' => 'Arif Santoso', 'username' => 'arifsantoso1', 'email' => 'arif.santoso1@polinema.ac.id'],
            ['nama' => 'Maya Wulandari', 'username' => 'mayawulandari1', 'email' => 'maya.wulandari1@polinema.ac.id'],
            ['nama' => 'Bayu Kurniawan', 'username' => 'bayukurniawan1', 'email' => 'bayu.kurniawan1@polinema.ac.id'],
            ['nama' => 'Rita Sari', 'username' => 'ritasari1', 'email' => 'rita.sari1@polinema.ac.id'],
            ['nama' => 'Fajar Pratama', 'username' => 'fajarpratama1', 'email' => 'fajar.pratama1@polinema.ac.id'],
            ['nama' => 'Tina Safitri', 'username' => 'tinasafitri1', 'email' => 'tina.safitri1@polinema.ac.id'],
            ['nama' => 'Yudi Santoso', 'username' => 'yudisantoso1', 'email' => 'yudi.santoso1@polinema.ac.id'],
            ['nama' => 'Sinta Puspita', 'username' => 'sintapuspita1', 'email' => 'sinta.puspita1@polinema.ac.id'],
            ['nama' => 'Rudi Nugroho', 'username' => 'rudinugroho1', 'email' => 'rudi.nugroho1@polinema.ac.id'],
            ['nama' => 'Lia Kurnia', 'username' => 'liakurnia1', 'email' => 'lia.kurnia1@polinema.ac.id'],
            ['nama' => 'Bima Hartono', 'username' => 'bimahartono1', 'email' => 'bima.hartono1@polinema.ac.id'],
            ['nama' => 'Rina Septiani', 'username' => 'rinaseptiani1', 'email' => 'rina.septiani1@polinema.ac.id'],
            ['nama' => 'Adi Pratama', 'username' => 'adipratama1', 'email' => 'adi.pratama1@polinema.ac.id'],
            ['nama' => 'Eka Wulandari', 'username' => 'ekawulandari1', 'email' => 'eka.wulandari1@polinema.ac.id'],
            ['nama' => 'Hasan Nugroho', 'username' => 'hasannugroho1', 'email' => 'hasan.nugroho1@polinema.ac.id'],
            ['nama' => 'Lita Sari', 'username' => 'litasari1', 'email' => 'lita.sari1@polinema.ac.id'],
            ['nama' => 'Dwi Kurniawan', 'username' => 'dwikurniawan1', 'email' => 'dwi.kurniawan1@polinema.ac.id'],
            ['nama' => 'Mira Safitri', 'username' => 'mirasafitri1', 'email' => 'mira.safitri1@polinema.ac.id'],
            ['nama' => 'Agung Nugroho', 'username' => 'agungnugroho1', 'email' => 'agung.nugroho1@polinema.ac.id'],
            ['nama' => 'Nia Pratama', 'username' => 'niapratama1', 'email' => 'nia.pratama1@polinema.ac.id'],
            ['nama' => 'Feri Santoso', 'username' => 'ferisantoso1', 'email' => 'feri.santoso1@polinema.ac.id'],
            ['nama' => 'Ayu Kurnia', 'username' => 'ayukurnia1', 'email' => 'ayu.kurnia1@polinema.ac.id'],
            ['nama' => 'Tono Pratama', 'username' => 'tonopratama1', 'email' => 'tono.pratama1@polinema.ac.id'],
            ['nama' => 'Mila Wulandari', 'username' => 'milawulandari1', 'email' => 'mila.wulandari1@polinema.ac.id'],
            ['nama' => 'Rudi Kurniawan', 'username' => 'rudikurniawan1', 'email' => 'rudi.kurniawan1@polinema.ac.id'],
            ['nama' => 'Siti Puspita', 'username' => 'sitipuspita1', 'email' => 'siti.puspita1@polinema.ac.id'],
            ['nama' => 'Eko Hartono', 'username' => 'ekohartono1', 'email' => 'eko.hartono1@polinema.ac.id'],
            ['nama' => 'Ayu Sari', 'username' => 'ayusari1', 'email' => 'ayu.sari1@polinema.ac.id'],
        ];
        foreach ($mahasiswa as $mhs) {
            $users[] = [
                'nama' => $mhs['nama'],
                'username' => $mhs['username'],
                'password' => Hash::make('password'),
                'email' => $mhs['email'],
                'level_id' => 2,
                'profile_photo' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ];
        }

        // 50 Dosen users
        $dosen = [
            ['nama' => 'Dr. Bambang Suharto', 'username' => 'bambangsuharto1', 'email' => 'bambang.suharto1@polinema.ac.id'],
            ['nama' => 'Dr. Ani Rahmawati', 'username' => 'anirahmawati1', 'email' => 'ani.rahmawati1@polinema.ac.id'],
            ['nama' => 'Dr. Joko Widodo', 'username' => 'jokowidodo1', 'email' => 'joko.widodo1@polinema.ac.id'],
            ['nama' => 'Dr. Sri Hartati', 'username' => 'srihartati1', 'email' => 'sri.hartati1@polinema.ac.id'],
            ['nama' => 'Dr. Wahyu Hidayat', 'username' => 'wahyuhidayat1', 'email' => 'wahyu.hidayat1@polinema.ac.id'],
            ['nama' => 'Dr. Rina Puspita', 'username' => 'rinapuspita2', 'email' => 'rina.puspita2@polinema.ac.id'],
            ['nama' => 'Dr. Adi Nugroho', 'username' => 'adinugroho2', 'email' => 'adi.nugroho2@polinema.ac.id'],
            ['nama' => 'Dr. Eka Sari', 'username' => 'ekasari2', 'email' => 'eka.sari2@polinema.ac.id'],
            ['nama' => 'Dr. Hasan Basri', 'username' => 'hasanbasri2', 'email' => 'hasan.basri2@polinema.ac.id'],
            ['nama' => 'Dr. Lita Dewi', 'username' => 'litadewi2', 'email' => 'lita.dewi2@polinema.ac.id'],
            ['nama' => 'Dr. Dwi Santoso', 'username' => 'dwisantoso2', 'email' => 'dwi.santoso2@polinema.ac.id'],
            ['nama' => 'Dr. Mira Andini', 'username' => 'miraandini2', 'email' => 'mira.andini2@polinema.ac.id'],
            ['nama' => 'Dr. Agung Pratama', 'username' => 'agungpratama2', 'email' => 'agung.pratama2@polinema.ac.id'],
            ['nama' => 'Dr. Nia Kurnia', 'username' => 'niakurnia2', 'email' => 'nia.kurnia2@polinema.ac.id'],
            ['nama' => 'Dr. Feri Irawan', 'username' => 'feriirawan2', 'email' => 'feri.irawan2@polinema.ac.id'],
            ['nama' => 'Dr. Ayu Safitri', 'username' => 'ayusafitri2', 'email' => 'ayu.safitri2@polinema.ac.id'],
            ['nama' => 'Dr. Tono Wijaya', 'username' => 'tonowijaya2', 'email' => 'tono.wijaya2@polinema.ac.id'],
            ['nama' => 'Dr. Mila Sari', 'username' => 'milasari2', 'email' => 'mila.sari2@polinema.ac.id'],
            ['nama' => 'Dr. Rudi Hermawan', 'username' => 'rudihermawan2', 'email' => 'rudi.hermawan2@polinema.ac.id'],
            ['nama' => 'Dr. Siti Fatimah', 'username' => 'sitifatimah2', 'email' => 'siti.fatimah2@polinema.ac.id'],
            ['nama' => 'Dr. Eko Susilo', 'username' => 'ekosusilo2', 'email' => 'eko.susilo2@polinema.ac.id'],
            ['nama' => 'Dr. Ayu Lestari', 'username' => 'ayulestari2', 'email' => 'ayu.lestari2@polinema.ac.id'],
            ['nama' => 'Dr. Bima Sakti', 'username' => 'bimasakti2', 'email' => 'bima.sakti2@polinema.ac.id'],
            ['nama' => 'Dr. Rina Kurniawati', 'username' => 'rinakurniawati2', 'email' => 'rina.kurniawati2@polinema.ac.id'],
            ['nama' => 'Dr. Hadi Santoso', 'username' => 'hadisantoso2', 'email' => 'hadi.santoso2@polinema.ac.id'],
            ['nama' => 'Dr. Lina Septiani', 'username' => 'linaseptiani2', 'email' => 'lina.septiani2@polinema.ac.id'],
            ['nama' => 'Dr. Andi Prasetyo', 'username' => 'andiprasetyo2', 'email' => 'andi.prasetyo2@polinema.ac.id'],
            ['nama' => 'Dr. Sari Indah', 'username' => 'sariindah2', 'email' => 'sari.indah2@polinema.ac.id'],
            ['nama' => 'Dr. Budi Hartono', 'username' => 'budihartono2', 'email' => 'budi.hartono2@polinema.ac.id'],
            ['nama' => 'Dr. Rina Wulandari', 'username' => 'rinawulandari2', 'email' => 'rina.wulandari2@polinema.ac.id'],
            ['nama' => 'Dr. Dedi Kurniawan', 'username' => 'dedikurniawan2', 'email' => 'dedi.kurniawan2@polinema.ac.id'],
            ['nama' => 'Dr. Lia Safitri', 'username' => 'liasafitri2', 'email' => 'lia.safitri2@polinema.ac.id'],
            ['nama' => 'Dr. Hendra Setiawan', 'username' => 'hendrasetiawan2', 'email' => 'hendra.setiawan2@polinema.ac.id'],
            ['nama' => 'Dr. Tina Marlina', 'username' => 'tinamarlina2', 'email' => 'tina.marlina2@polinema.ac.id'],
            ['nama' => 'Dr. Fajar Nugroho', 'username' => 'fajarnugroho2', 'email' => 'fajar.nugroho2@polinema.ac.id'],
            ['nama' => 'Dr. Mira Puspita', 'username' => 'mirapuspita2', 'email' => 'mira.puspita2@polinema.ac.id'],
            ['nama' => 'Dr. Rudi Pratama', 'username' => 'rudipratama2', 'email' => 'rudi.pratama2@polinema.ac.id'],
            ['nama' => 'Dr. Siti Rahayu', 'username' => 'sitirahayu2', 'email' => 'siti.rahayu2@polinema.ac.id'],
            ['nama' => 'Dr. Eko Wahyudi', 'username' => 'ekowahyudi2', 'email' => 'eko.wahyudi2@polinema.ac.id'],
            ['nama' => 'Dr. Ayu Permata', 'username' => 'ayupermata2', 'email' => 'ayu.permata2@polinema.ac.id'],
            ['nama' => 'Dr. Bima Nugroho', 'username' => 'bimanugroho2', 'email' => 'bima.nugroho2@polinema.ac.id'],
            ['nama' => 'Dr. Rina Anggraini', 'username' => 'rinaanggraini2', 'email' => 'rina.anggraini2@polinema.ac.id'],
            ['nama' => 'Dr. Hadi Kurniawan', 'username' => 'hadikurniawan2', 'email' => 'hadi.kurniawan2@polinema.ac.id'],
            ['nama' => 'Dr. Lina Wulandari', 'username' => 'linawulandari2', 'email' => 'lina.wulandari2@polinema.ac.id'],
            ['nama' => 'Dr. Ahmad Zaki', 'username' => 'ahmadzaki2', 'email' => 'ahmad.zaki2@polinema.ac.id'],
            ['nama' => 'Dr. Dewi Safitri', 'username' => 'dewifitri2', 'email' => 'dewi.safitri2@polinema.ac.id'],
            ['nama' => 'Dr. Rizki Maulana', 'username' => 'rizkimaulana2', 'email' => 'rizki.maulana2@polinema.ac.id'],
            ['nama' => 'Dr. Fitri Anggraini', 'username' => 'fitrianggraini2', 'email' => 'fitri.anggraini2@polinema.ac.id'],
            ['nama' => 'Dr. Eko Pratama', 'username' => 'ekopratama2', 'email' => 'eko.pratama2@polinema.ac.id'],
            ['nama' => 'Dr. Sari Kurnia', 'username' => 'sarikurnia2', 'email' => 'sari.kurnia2@polinema.ac.id'],
        ];
        foreach ($dosen as $dsn) {
            $users[] = [
                'nama' => $dsn['nama'],
                'username' => $dsn['username'],
                'password' => Hash::make('password'),
                'email' => $dsn['email'],
                'level_id' => 3,
                'profile_photo' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ];
        }

        // 30 Tendik users
        $tendik = [
            ['nama' => 'Rudi Hermawan', 'username' => 'rudihermawan3', 'email' => 'rudi.hermawan3@example.com'],
            ['nama' => 'Siti Fatimah', 'username' => 'sitifatimah3', 'email' => 'siti.fatimah3@example.com'],
            ['nama' => 'Eko Susilo', 'username' => 'ekosusilo3', 'email' => 'eko.susilo3@example.com'],
            ['nama' => 'Ayu Lestari', 'username' => 'ayulestari3', 'email' => 'ayu.lestari3@example.com'],
            ['nama' => 'Bima Sakti', 'username' => 'bimasakti3', 'email' => 'bima.sakti3@example.com'],
            ['nama' => 'Rina Kurniawati', 'username' => 'rinakurniawati3', 'email' => 'rina.kurniawati3@example.com'],
            ['nama' => 'Hadi Santoso', 'username' => 'hadisantoso3', 'email' => 'hadi.santoso3@example.com'],
            ['nama' => 'Lina Septiani', 'username' => 'linaseptiani3', 'email' => 'lina.septiani3@example.com'],
            ['nama' => 'Tono Wijaya', 'username' => 'tonowijaya3', 'email' => 'tono.wijaya3@example.com'],
            ['nama' => 'Mila Sari', 'username' => 'milasari3', 'email' => 'mila.sari3@example.com'],
            ['nama' => 'Andi Prasetyo', 'username' => 'andiprasetyo3', 'email' => 'andi.prasetyo3@example.com'],
            ['nama' => 'Sari Indah', 'username' => 'sariindah3', 'email' => 'sari.indah3@example.com'],
            ['nama' => 'Budi Hartono', 'username' => 'budihartono3', 'email' => 'budi.hartono3@example.com'],
            ['nama' => 'Rina Wulandari', 'username' => 'rinawulandari3', 'email' => 'rina.wulandari3@example.com'],
            ['nama' => 'Dedi Kurniawan', 'username' => 'dedikurniawan3', 'email' => 'dedi.kurniawan3@example.com'],
            ['nama' => 'Lia Safitri', 'username' => 'liasafitri3', 'email' => 'lia.safitri3@example.com'],
            ['nama' => 'Hendra Setiawan', 'username' => 'hendrasetiawan3', 'email' => 'hendra.setiawan3@example.com'],
            ['nama' => 'Tina Marlina', 'username' => 'tinamarlina3', 'email' => 'tina.marlina3@example.com'],
            ['nama' => 'Fajar Nugroho', 'username' => 'fajarnugroho3', 'email' => 'fajar.nugroho3@example.com'],
            ['nama' => 'Mira Puspita', 'username' => 'mirapuspita3', 'email' => 'mira.puspita3@example.com'],
            ['nama' => 'Rudi Pratama', 'username' => 'rudipratama3', 'email' => 'rudi.pratama3@example.com'],
            ['nama' => 'Siti Rahayu', 'username' => 'sitirahayu3', 'email' => 'siti.rahayu3@example.com'],
            ['nama' => 'Eko Wahyudi', 'username' => 'ekowahyudi3', 'email' => 'eko.wahyudi3@example.com'],
            ['nama' => 'Ayu Permata', 'username' => 'ayupermata3', 'email' => 'ayu.permata3@example.com'],
            ['nama' => 'Bima Nugroho', 'username' => 'bimanugroho3', 'email' => 'bima.nugroho3@example.com'],
            ['nama' => 'Rina Anggraini', 'username' => 'rinaanggraini3', 'email' => 'rina.anggraini3@example.com'],
            ['nama' => 'Hadi Kurniawan', 'username' => 'hadikurniawan3', 'email' => 'hadi.kurniawan3@example.com'],
            ['nama' => 'Lina Wulandari', 'username' => 'linawulandari3', 'email' => 'lina.wulandari3@example.com'],
            ['nama' => 'Ahmad Zaki', 'username' => 'ahmadzaki3', 'email' => 'ahmad.zaki3@example.com'],
            ['nama' => 'Dewi Safitri', 'username' => 'dewifitri3', 'email' => 'dewi.safitri3@example.com'],
        ];
        foreach ($tendik as $tdk) {
            $users[] = [
                'nama' => $tdk['nama'],
                'username' => $tdk['username'],
                'password' => Hash::make('password'),
                'email' => $tdk['email'],
                'level_id' => 4,
                'profile_photo' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ];
        }

        // 30 Sarpras users
        $sarpras = [
            ['nama' => 'Andi Prasetyo', 'username' => 'andiprasetyo4', 'email' => 'andi.prasetyo4@example.com'],
            ['nama' => 'Sari Indah', 'username' => 'sariindah4', 'email' => 'sari.indah4@example.com'],
            ['nama' => 'Budi Hartono', 'username' => 'budihartono4', 'email' => 'budi.hartono4@example.com'],
            ['nama' => 'Rina Wulandari', 'username' => 'rinawulandari4', 'email' => 'rina.wulandari4@example.com'],
            ['nama' => 'Dedi Kurniawan', 'username' => 'dedikurniawan4', 'email' => 'dedi.kurniawan4@example.com'],
            ['nama' => 'Lia Safitri', 'username' => 'liasafitri4', 'email' => 'lia.safitri4@example.com'],
            ['nama' => 'Hendra Setiawan', 'username' => 'hendrasetiawan4', 'email' => 'hendra.setiawan4@example.com'],
            ['nama' => 'Tina Marlina', 'username' => 'tinamarlina4', 'email' => 'tina.marlina4@example.com'],
            ['nama' => 'Fajar Nugroho', 'username' => 'fajarnugroho4', 'email' => 'fajar.nugroho4@example.com'],
            ['nama' => 'Mira Puspita', 'username' => 'mirapuspita4', 'email' => 'mira.puspita4@example.com'],
            ['nama' => 'Rudi Pratama', 'username' => 'rudipratama4', 'email' => 'rudi.pratama4@example.com'],
            ['nama' => 'Siti Rahayu', 'username' => 'sitirahayu4', 'email' => 'siti.rahayu4@example.com'],
            ['nama' => 'Eko Wahyudi', 'username' => 'ekowahyudi4', 'email' => 'eko.wahyudi4@example.com'],
            ['nama' => 'Ayu Permata', 'username' => 'ayupermata4', 'email' => 'ayu.permata4@example.com'],
            ['nama' => 'Bima Nugroho', 'username' => 'bimanugroho4', 'email' => 'bima.nugroho4@example.com'],
            ['nama' => 'Rina Anggraini', 'username' => 'rinaanggraini4', 'email' => 'rina.anggraini4@example.com'],
            ['nama' => 'Hadi Kurniawan', 'username' => 'hadikurniawan4', 'email' => 'hadi.kurniawan4@example.com'],
            ['nama' => 'Lina Wulandari', 'username' => 'linawulandari4', 'email' => 'lina.wulandari4@example.com'],
            ['nama' => 'Ahmad Zaki', 'username' => 'ahmadzaki4', 'email' => 'ahmad.zaki4@example.com'],
            ['nama' => 'Dewi Safitri', 'username' => 'dewifitri4', 'email' => 'dewi.safitri4@example.com'],
            ['nama' => 'Rizki Maulana', 'username' => 'rizkimaulana4', 'email' => 'rizki.maulana4@example.com'],
            ['nama' => 'Fitri Anggraini', 'username' => 'fitrianggraini4', 'email' => 'fitri.anggraini4@example.com'],
            ['nama' => 'Eko Pratama', 'username' => 'ekopratama4', 'email' => 'eko.pratama4@example.com'],
            ['nama' => 'Sari Kurnia', 'username' => 'sarikurnia4', 'email' => 'sari.kurnia4@example.com'],
            ['nama' => 'Hendra Wijaya', 'username' => 'hendrawijaya4', 'email' => 'hendra.wijaya4@example.com'],
            ['nama' => 'Lina Puspita', 'username' => 'linapuspita4', 'email' => 'lina.puspita4@example.com'],
            ['nama' => 'Dedi Nugroho', 'username' => 'dedinugroho4', 'email' => 'dedi.nugroho4@example.com'],
            ['nama' => 'Nia Safitri', 'username' => 'niasafitri4', 'email' => 'nia.safitri4@example.com'],
            ['nama' => 'Arif Santoso', 'username' => 'arifsantoso4', 'email' => 'arif.santoso4@example.com'],
            ['nama' => 'Maya Wulandari', 'username' => 'mayawulandari4', 'email' => 'maya.wulandari4@example.com'],
        ];
        foreach ($sarpras as $srp) {
            $users[] = [
                'nama' => $srp['nama'],
                'username' => $srp['username'],
                'password' => Hash::make('password'),
                'email' => $srp['email'],
                'level_id' => 5,
                'profile_photo' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ];
        }

        // 20 Teknisi users
        $teknisi = [
            ['nama' => 'Rudi Pratama', 'username' => 'rudipratama5', 'email' => 'rudi.pratama5@polinema.ac.id'],
            ['nama' => 'Siti Rahayu', 'username' => 'sitirahayu5', 'email' => 'siti.rahayu5@polinema.ac.id'],
            ['nama' => 'Eko Wahyudi', 'username' => 'ekowahyudi5', 'email' => 'eko.wahyudi5@polinema.ac.id'],
            ['nama' => 'Ayu Permata', 'username' => 'ayupermata5', 'email' => 'ayu.permata5@polinema.ac.id'],
            ['nama' => 'Bima Nugroho', 'username' => 'bimanugroho5', 'email' => 'bima.nugroho5@polinema.ac.id'],
            ['nama' => 'Rina Anggraini', 'username' => 'rinaanggraini5', 'email' => 'rina.anggraini5@polinema.ac.id'],
            ['nama' => 'Hadi Kurniawan', 'username' => 'hadikurniawan5', 'email' => 'hadi.kurniawan5@polinema.ac.id'],
            ['nama' => 'Lina Wulandari', 'username' => 'linawulandari5', 'email' => 'lina.wulandari5@polinema.ac.id'],
            ['nama' => 'Ahmad Zaki', 'username' => 'ahmadzaki5', 'email' => 'ahmad.zaki5@polinema.ac.id'],
            ['nama' => 'Dewi Safitri', 'username' => 'dewifitri5', 'email' => 'dewi.safitri5@polinema.ac.id'],
            ['nama' => 'Rizki Maulana', 'username' => 'rizkimaulana5', 'email' => 'rizki.maulana5@polinema.ac.id'],
            ['nama' => 'Fitri Anggraini', 'username' => 'fitrianggraini5', 'email' => 'fitri.anggraini5@polinema.ac.id'],
            ['nama' => 'Eko Pratama', 'username' => 'ekopratama5', 'email' => 'eko.pratama5@polinema.ac.id'],
            ['nama' => 'Sari Kurnia', 'username' => 'sarikurnia5', 'email' => 'sari.kurnia5@polinema.ac.id'],
            ['nama' => 'Hendra Wijaya', 'username' => 'hendrawijaya5', 'email' => 'hendra.wijaya5@polinema.ac.id'],
            ['nama' => 'Lina Puspita', 'username' => 'linapuspita5', 'email' => 'lina.puspita5@polinema.ac.id'],
            ['nama' => 'Dedi Nugroho', 'username' => 'dedinugroho5', 'email' => 'dedi.nugroho5@polinema.ac.id'],
            ['nama' => 'Nia Safitri', 'username' => 'niasafitri5', 'email' => 'nia.safitri5@polinema.ac.id'],
            ['nama' => 'Arif Santoso', 'username' => 'arifsantoso5', 'email' => 'arif.santoso5@polinema.ac.id'],
            ['nama' => 'Maya Wulandari', 'username' => 'mayawulandari5', 'email' => 'maya.wulandari5@polinema.ac.id'],
        ];
        foreach ($teknisi as $tkn) {
            $users[] = [
                'nama' => $tkn['nama'],
                'username' => $tkn['username'],
                'password' => Hash::make('password'),
                'email' => $tkn['email'],
                'level_id' => 6,
                'profile_photo' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ];
        }

        // Insert all users into the database
        UserModel::insert($users);
    }
}