<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('t_rekomendasi_mahasiswa', function (Blueprint $table) {
            $table->id('rekom_id');
            $table->unsignedBigInteger(column: 'laporan_id');
            $table->json('nilai_kriteria'); // Auto-generated by system
            $table->decimal('skor_total', 8, 2); // Hasil perhitungan
            $table->timestamps();
            
            $table->foreign(columns: 'laporan_id')->references('laporan_id')->on('t_laporan')->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('t_rekomendasi_mahasiswa');
    }
};
